export const countries = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brazil" },
  { code: "BN", name: "Brunei" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cape Verde" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "CD", name: "Democratic Republic of the Congo" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "FK", name: "Falkland Islands" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Greece" },
  { code: "GD", name: "Grenada" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "XK", name: "Kosovo" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Laos" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia" },
  { code: "MD", name: "Moldova" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "North Macedonia" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestine" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "CG", name: "Republic of the Congo" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russia" },
  { code: "RW", name: "Rwanda" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "KR", name: "South Korea" },
  { code: "SS", name: "South Sudan" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syria" },
  { code: "TW", name: "Taiwan" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TH", name: "Thailand" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
];

export const statesByCountry: Record<string, { code: string; name: string }[]> =
  {
    US: [
      { code: "AL", name: "Alabama" },
      { code: "AK", name: "Alaska" },
      { code: "AZ", name: "Arizona" },
      { code: "AR", name: "Arkansas" },
      { code: "CA", name: "California" },
      { code: "CO", name: "Colorado" },
      { code: "CT", name: "Connecticut" },
      { code: "DE", name: "Delaware" },
      { code: "FL", name: "Florida" },
      { code: "GA", name: "Georgia" },
      { code: "HI", name: "Hawaii" },
      { code: "ID", name: "Idaho" },
      { code: "IL", name: "Illinois" },
      { code: "IN", name: "Indiana" },
      { code: "IA", name: "Iowa" },
      { code: "KS", name: "Kansas" },
      { code: "KY", name: "Kentucky" },
      { code: "LA", name: "Louisiana" },
      { code: "ME", name: "Maine" },
      { code: "MD", name: "Maryland" },
      { code: "MA", name: "Massachusetts" },
      { code: "MI", name: "Michigan" },
      { code: "MN", name: "Minnesota" },
      { code: "MS", name: "Mississippi" },
      { code: "MO", name: "Missouri" },
      { code: "MT", name: "Montana" },
      { code: "NE", name: "Nebraska" },
      { code: "NV", name: "Nevada" },
      { code: "NH", name: "New Hampshire" },
      { code: "NJ", name: "New Jersey" },
      { code: "NM", name: "New Mexico" },
      { code: "NY", name: "New York" },
      { code: "NC", name: "North Carolina" },
      { code: "ND", name: "North Dakota" },
      { code: "OH", name: "Ohio" },
      { code: "OK", name: "Oklahoma" },
      { code: "OR", name: "Oregon" },
      { code: "PA", name: "Pennsylvania" },
      { code: "RI", name: "Rhode Island" },
      { code: "SC", name: "South Carolina" },
      { code: "SD", name: "South Dakota" },
      { code: "TN", name: "Tennessee" },
      { code: "TX", name: "Texas" },
      { code: "UT", name: "Utah" },
      { code: "VT", name: "Vermont" },
      { code: "VA", name: "Virginia" },
      { code: "WA", name: "Washington" },
      { code: "WV", name: "West Virginia" },
      { code: "WI", name: "Wisconsin" },
      { code: "WY", name: "Wyoming" },
    ],
    CA: [
      { code: "AB", name: "Alberta" },
      { code: "BC", name: "British Columbia" },
      { code: "MB", name: "Manitoba" },
      { code: "NB", name: "New Brunswick" },
      { code: "NL", name: "Newfoundland and Labrador" },
      { code: "NS", name: "Nova Scotia" },
      { code: "ON", name: "Ontario" },
      { code: "PE", name: "Prince Edward Island" },
      { code: "QC", name: "Quebec" },
      { code: "SK", name: "Saskatchewan" },
      { code: "NT", name: "Northwest Territories" },
      { code: "NU", name: "Nunavut" },
      { code: "YT", name: "Yukon" },
    ],
    NG: [
      { code: "AB", name: "Abia" },
      { code: "AD", name: "Adamawa" },
      { code: "AK", name: "Akwa Ibom" },
      { code: "AN", name: "Anambra" },
      { code: "BA", name: "Bauchi" },
      { code: "BY", name: "Bayelsa" },
      { code: "BE", name: "Benue" },
      { code: "BO", name: "Borno" },
      { code: "CR", name: "Cross River" },
      { code: "DE", name: "Delta" },
      { code: "EB", name: "Ebonyi" },
      { code: "ED", name: "Edo" },
      { code: "EK", name: "Ekiti" },
      { code: "EN", name: "Enugu" },
      { code: "GO", name: "Gombe" },
      { code: "IM", name: "Imo" },
      { code: "JI", name: "Jigawa" },
      { code: "KD", name: "Kaduna" },
      { code: "KN", name: "Kano" },
      { code: "KT", name: "Katsina" },
      { code: "KE", name: "Kebbi" },
      { code: "KO", name: "Kogi" },
      { code: "KW", name: "Kwara" },
      { code: "LA", name: "Lagos" },
      { code: "NA", name: "Nasarawa" },
      { code: "NI", name: "Niger" },
      { code: "OG", name: "Ogun" },
      { code: "ON", name: "Ondo" },
      { code: "OS", name: "Osun" },
      { code: "OY", name: "Oyo" },
      { code: "PL", name: "Plateau" },
      { code: "RI", name: "Rivers" },
      { code: "SO", name: "Sokoto" },
      { code: "TA", name: "Taraba" },
      { code: "YO", name: "Yobe" },
      { code: "ZA", name: "Zamfara" },
      { code: "FC", name: "Federal Capital Territory" },
    ],
    AU: [
      { code: "NSW", name: "New South Wales" },
      { code: "QLD", name: "Queensland" },
      { code: "SA", name: "South Australia" },
      { code: "TAS", name: "Tasmania" },
      { code: "VIC", name: "Victoria" },
      { code: "WA", name: "Western Australia" },
      { code: "ACT", name: "Australian Capital Territory" },
      { code: "NT", name: "Northern Territory" },
    ],
    GB: [
      { code: "ENG", name: "England" },
      { code: "SCT", name: "Scotland" },
      { code: "WLS", name: "Wales" },
      { code: "NIR", name: "Northern Ireland" },
    ],
    IN: [
      { code: "AP", name: "Andhra Pradesh" },
      { code: "AR", name: "Arunachal Pradesh" },
      { code: "AS", name: "Assam" },
      { code: "BR", name: "Bihar" },
      { code: "CT", name: "Chhattisgarh" },
      { code: "GA", name: "Goa" },
      { code: "GJ", name: "Gujarat" },
      { code: "HR", name: "Haryana" },
      { code: "HP", name: "Himachal Pradesh" },
      { code: "JK", name: "Jammu and Kashmir" },
      { code: "JH", name: "Jharkhand" },
      { code: "KA", name: "Karnataka" },
      { code: "KL", name: "Kerala" },
      { code: "MP", name: "Madhya Pradesh" },
      { code: "MH", name: "Maharashtra" },
      { code: "MN", name: "Manipur" },
      { code: "ML", name: "Meghalaya" },
      { code: "MZ", name: "Mizoram" },
      { code: "NL", name: "Nagaland" },
      { code: "OR", name: "Odisha" },
      { code: "PB", name: "Punjab" },
      { code: "RJ", name: "Rajasthan" },
      { code: "SK", name: "Sikkim" },
      { code: "TN", name: "Tamil Nadu" },
      { code: "TG", name: "Telangana" },
      { code: "TR", name: "Tripura" },
      { code: "UP", name: "Uttar Pradesh" },
      { code: "UT", name: "Uttarakhand" },
      { code: "WB", name: "West Bengal" },
      { code: "AN", name: "Andaman and Nicobar Islands" },
      { code: "CH", name: "Chandigarh" },
      { code: "DN", name: "Dadra and Nagar Haveli" },
      { code: "DD", name: "Daman and Diu" },
      { code: "DL", name: "Delhi" },
      { code: "LD", name: "Lakshadweep" },
      { code: "PY", name: "Puducherry" },
    ],
    BR: [
      { code: "AC", name: "Acre" },
      { code: "AL", name: "Alagoas" },
      { code: "AP", name: "Amapá" },
      { code: "AM", name: "Amazonas" },
      { code: "BA", name: "Bahia" },
      { code: "CE", name: "Ceará" },
      { code: "DF", name: "Distrito Federal" },
      { code: "ES", name: "Espírito Santo" },
      { code: "GO", name: "Goiás" },
      { code: "MA", name: "Maranhão" },
      { code: "MT", name: "Mato Grosso" },
      { code: "MS", name: "Mato Grosso do Sul" },
      { code: "MG", name: "Minas Gerais" },
      { code: "PA", name: "Pará" },
      { code: "PB", name: "Paraíba" },
      { code: "PR", name: "Paraná" },
      { code: "PE", name: "Pernambuco" },
      { code: "PI", name: "Piauí" },
      { code: "RJ", name: "Rio de Janeiro" },
      { code: "RN", name: "Rio Grande do Norte" },
      { code: "RS", name: "Rio Grande do Sul" },
      { code: "RO", name: "Rondônia" },
      { code: "RR", name: "Roraima" },
      { code: "SC", name: "Santa Catarina" },
      { code: "SP", name: "São Paulo" },
      { code: "SE", name: "Sergipe" },
      { code: "TO", name: "Tocantins" },
    ],
    MX: [
      { code: "AGU", name: "Aguascalientes" },
      { code: "BCN", name: "Baja California" },
      { code: "BCS", name: "Baja California Sur" },
      { code: "CAM", name: "Campeche" },
      { code: "CHP", name: "Chiapas" },
      { code: "CHH", name: "Chihuahua" },
      { code: "COA", name: "Coahuila" },
      { code: "COL", name: "Colima" },
      { code: "DUR", name: "Durango" },
      { code: "GUA", name: "Guanajuato" },
      { code: "GRO", name: "Guerrero" },
      { code: "HID", name: "Hidalgo" },
      { code: "JAL", name: "Jalisco" },
      { code: "MEX", name: "México" },
      { code: "MIC", name: "Michoacán" },
      { code: "MOR", name: "Morelos" },
      { code: "NAY", name: "Nayarit" },
      { code: "NLE", name: "Nuevo León" },
      { code: "OAX", name: "Oaxaca" },
      { code: "PUE", name: "Puebla" },
      { code: "QUE", name: "Querétaro" },
      { code: "ROO", name: "Quintana Roo" },
      { code: "SLP", name: "San Luis Potosí" },
      { code: "SIN", name: "Sinaloa" },
      { code: "SON", name: "Sonora" },
      { code: "TAB", name: "Tabasco" },
      { code: "TAM", name: "Tamaulipas" },
      { code: "TLA", name: "Tlaxcala" },
      { code: "VER", name: "Veracruz" },
      { code: "YUC", name: "Yucatán" },
      { code: "ZAC", name: "Zacatecas" },
      { code: "CMX", name: "Ciudad de México" },
    ],
    DE: [
      { code: "BW", name: "Baden-Württemberg" },
      { code: "BY", name: "Bayern" },
      { code: "BE", name: "Berlin" },
      { code: "BB", name: "Brandenburg" },
      { code: "HB", name: "Bremen" },
      { code: "HH", name: "Hamburg" },
      { code: "HE", name: "Hessen" },
      { code: "MV", name: "Mecklenburg-Vorpommern" },
      { code: "NI", name: "Niedersachsen" },
      { code: "NW", name: "Nordrhein-Westfalen" },
      { code: "RP", name: "Rheinland-Pfalz" },
      { code: "SL", name: "Saarland" },
      { code: "SN", name: "Sachsen" },
      { code: "ST", name: "Sachsen-Anhalt" },
      { code: "SH", name: "Schleswig-Holstein" },
      { code: "TH", name: "Thüringen" },
    ],
    ZA: [
      { code: "EC", name: "Eastern Cape" },
      { code: "FS", name: "Free State" },
      { code: "GP", name: "Gauteng" },
      { code: "KZN", name: "KwaZulu-Natal" },
      { code: "LP", name: "Limpopo" },
      { code: "MP", name: "Mpumalanga" },
      { code: "NC", name: "Northern Cape" },
      { code: "NW", name: "North West" },
      { code: "WC", name: "Western Cape" },
    ],
    AR: [
      { code: "BA", name: "Buenos Aires" },
      { code: "CT", name: "Catamarca" },
      { code: "CH", name: "Chaco" },
      { code: "CU", name: "Chubut" },
      { code: "CB", name: "Córdoba" },
      { code: "CR", name: "Corrientes" },
      { code: "ER", name: "Entre Ríos" },
      { code: "FO", name: "Formosa" },
      { code: "JY", name: "Jujuy" },
      { code: "LP", name: "La Pampa" },
      { code: "LR", name: "La Rioja" },
      { code: "MZ", name: "Mendoza" },
      { code: "MN", name: "Misiones" },
      { code: "NQ", name: "Neuquén" },
      { code: "RN", name: "Río Negro" },
      { code: "SA", name: "Salta" },
      { code: "SJ", name: "San Juan" },
      { code: "SL", name: "San Luis" },
      { code: "SC", name: "Santa Cruz" },
      { code: "SF", name: "Santa Fe" },
      { code: "SE", name: "Santiago del Estero" },
      { code: "TF", name: "Tierra del Fuego" },
      { code: "TM", name: "Tucumán" },
      { code: "CF", name: "Ciudad Autónoma de Buenos Aires" },
    ],
    IT: [
      { code: "AG", name: "Agrigento" },
      { code: "AL", name: "Alessandria" },
      { code: "AN", name: "Ancona" },
      { code: "AO", name: "Aosta" },
      { code: "AR", name: "Arezzo" },
      { code: "AP", name: "Ascoli Piceno" },
      { code: "AT", name: "Asti" },
      { code: "AV", name: "Avellino" },
      { code: "BA", name: "Bari" },
      { code: "BT", name: "Barletta-Andria-Trani" },
      { code: "BL", name: "Belluno" },
      { code: "BN", name: "Benevento" },
      { code: "BG", name: "Bergamo" },
      { code: "BI", name: "Biella" },
      { code: "BO", name: "Bologna" },
      { code: "BZ", name: "Bolzano" },
      { code: "BS", name: "Brescia" },
      { code: "BR", name: "Brindisi" },
      { code: "CA", name: "Cagliari" },
      { code: "CL", name: "Caltanissetta" },
      { code: "CB", name: "Campobasso" },
      { code: "CE", name: "Caserta" },
      { code: "CT", name: "Catania" },
      { code: "CZ", name: "Catanzaro" },
      { code: "CH", name: "Chieti" },
      { code: "CO", name: "Como" },
      { code: "CS", name: "Cosenza" },
      { code: "CR", name: "Cremona" },
      { code: "KR", name: "Crotone" },
      { code: "CN", name: "Cuneo" },
      { code: "EN", name: "Enna" },
      { code: "FM", name: "Fermo" },
      { code: "FE", name: "Ferrara" },
      { code: "FI", name: "Firenze" },
      { code: "FG", name: "Foggia" },
      { code: "FC", name: "Forlì-Cesena" },
      { code: "FR", name: "Frosinone" },
      { code: "GE", name: "Genova" },
      { code: "GO", name: "Gorizia" },
      { code: "GR", name: "Grosseto" },
      { code: "IM", name: "Imperia" },
      { code: "IS", name: "Isernia" },
      { code: "AQ", name: "L'Aquila" },
      { code: "SP", name: "La Spezia" },
      { code: "LT", name: "Latina" },
      { code: "LE", name: "Lecce" },
      { code: "LC", name: "Lecco" },
      { code: "LI", name: "Livorno" },
      { code: "LO", name: "Lodi" },
      { code: "LU", name: "Lucca" },
      { code: "MC", name: "Macerata" },
      { code: "MN", name: "Mantova" },
      { code: "MS", name: "Massa-Carrara" },
      { code: "MT", name: "Matera" },
      { code: "ME", name: "Messina" },
      { code: "MI", name: "Milano" },
      { code: "MO", name: "Modena" },
      { code: "MB", name: "Monza e Brianza" },
      { code: "NA", name: "Napoli" },
      { code: "NO", name: "Novara" },
      { code: "NU", name: "Nuoro" },
      { code: "OR", name: "Oristano" },
      { code: "PD", name: "Padova" },
      { code: "PA", name: "Palermo" },
      { code: "PR", name: "Parma" },
      { code: "PV", name: "Pavia" },
      { code: "PG", name: "Perugia" },
      { code: "PU", name: "Pesaro e Urbino" },
      { code: "PE", name: "Pescara" },
      { code: "PC", name: "Piacenza" },
      { code: "PI", name: "Pisa" },
      { code: "PT", name: "Pistoia" },
      { code: "PN", name: "Pordenone" },
      { code: "PZ", name: "Potenza" },
      { code: "PO", name: "Prato" },
      { code: "RG", name: "Ragusa" },
      { code: "RA", name: "Ravenna" },
      { code: "RC", name: "Reggio Calabria" },
      { code: "RE", name: "Reggio Emilia" },
      { code: "RI", name: "Rieti" },
      { code: "RN", name: "Rimini" },
      { code: "RM", name: "Roma" },
      { code: "RO", name: "Rovigo" },
      { code: "SA", name: "Salerno" },
      { code: "SS", name: "Sassari" },
      { code: "SV", name: "Savona" },
      { code: "SI", name: "Siena" },
      { code: "SR", name: "Siracusa" },
      { code: "SO", name: "Sondrio" },
      { code: "SU", name: "Sud Sardegna" },
      { code: "TA", name: "Taranto" },
      { code: "TE", name: "Teramo" },
      { code: "TR", name: "Terni" },
      { code: "TO", name: "Torino" },
      { code: "TP", name: "Trapani" },
      { code: "TN", name: "Trento" },
      { code: "TV", name: "Treviso" },
      { code: "TS", name: "Trieste" },
      { code: "UD", name: "Udine" },
      { code: "VA", name: "Varese" },
      { code: "VE", name: "Venezia" },
      { code: "VB", name: "Verbano-Cusio-Ossola" },
      { code: "VC", name: "Vercelli" },
      { code: "VR", name: "Verona" },
      { code: "VV", name: "Vibo Valentia" },
      { code: "VI", name: "Vicenza" },
      { code: "VT", name: "Viterbo" },
    ],
    ES: [
      { code: "AN", name: "Andalucía" },
      { code: "AR", name: "Aragón" },
      { code: "AS", name: "Asturias" },
      { code: "IB", name: "Baleares" },
      { code: "CN", name: "Canarias" },
      { code: "CB", name: "Cantabria" },
      { code: "CM", name: "Castilla-La Mancha" },
      { code: "CL", name: "Castilla y León" },
      { code: "CT", name: "Cataluña" },
      { code: "EX", name: "Extremadura" },
      { code: "GA", name: "Galicia" },
      { code: "MD", name: "Madrid" },
      { code: "MC", name: "Murcia" },
      { code: "NC", name: "Navarra" },
      { code: "PV", name: "País Vasco" },
      { code: "RI", name: "La Rioja" },
      { code: "VC", name: "Valencia" },
      { code: "CE", name: "Ceuta" },
      { code: "ML", name: "Melilla" },
    ],
    FR: [
      { code: "01", name: "Ain" },
      { code: "02", name: "Aisne" },
      { code: "03", name: "Allier" },
      { code: "04", name: "Alpes-de-Haute-Provence" },
      { code: "05", name: "Hautes-Alpes" },
      { code: "06", name: "Alpes-Maritimes" },
      { code: "07", name: "Ardèche" },
      { code: "08", name: "Ardennes" },
      { code: "09", name: "Ariège" },
      { code: "10", name: "Aube" },
      { code: "11", name: "Aude" },
      { code: "12", name: "Aveyron" },
      { code: "13", name: "Bouches-du-Rhône" },
      { code: "14", name: "Calvados" },
      { code: "15", name: "Cantal" },
      { code: "16", name: "Charente" },
      { code: "17", name: "Charente-Maritime" },
      { code: "18", name: "Cher" },
      { code: "19", name: "Corrèze" },
      { code: "2A", name: "Corse-du-Sud" },
      { code: "2B", name: "Haute-Corse" },
      { code: "21", name: "Côte-d'Or" },
      { code: "22", name: "Côtes-d'Armor" },
      { code: "23", name: "Creuse" },
      { code: "24", name: "Dordogne" },
      { code: "25", name: "Doubs" },
      { code: "26", name: "Drôme" },
      { code: "27", name: "Eure" },
      { code: "28", name: "Eure-et-Loir" },
      { code: "29", name: "Finistère" },
      { code: "30", name: "Gard" },
      { code: "31", name: "Haute-Garonne" },
      { code: "32", name: "Gers" },
      { code: "33", name: "Gironde" },
      { code: "34", name: "Hérault" },
      { code: "35", name: "Ille-et-Vilaine" },
      { code: "36", name: "Indre" },
      { code: "37", name: "Indre-et-Loire" },
      { code: "38", name: "Isère" },
      { code: "39", name: "Jura" },
      { code: "40", name: "Landes" },
      { code: "41", name: "Loir-et-Cher" },
      { code: "42", name: "Loire" },
      { code: "43", name: "Haute-Loire" },
      { code: "44", name: "Loire-Atlantique" },
      { code: "45", name: "Loiret" },
      { code: "46", name: "Lot" },
      { code: "47", name: "Lot-et-Garonne" },
      { code: "48", name: "Lozère" },
      { code: "49", name: "Maine-et-Loire" },
      { code: "50", name: "Manche" },
      { code: "51", name: "Marne" },
      { code: "52", name: "Haute-Marne" },
      { code: "53", name: "Mayenne" },
      { code: "54", name: "Meurthe-et-Moselle" },
      { code: "55", name: "Meuse" },
      { code: "56", name: "Morbihan" },
      { code: "57", name: "Moselle" },
      { code: "58", name: "Nièvre" },
      { code: "59", name: "Nord" },
      { code: "60", name: "Oise" },
      { code: "61", name: "Orne" },
      { code: "62", name: "Pas-de-Calais" },
      { code: "63", name: "Puy-de-Dôme" },
      { code: "64", name: "Pyrénées-Atlantiques" },
      { code: "65", name: "Hautes-Pyrénées" },
      { code: "66", name: "Pyrénées-Orientales" },
      { code: "67", name: "Bas-Rhin" },
      { code: "68", name: "Haut-Rhin" },
      { code: "69", name: "Rhône" },
      { code: "70", name: "Haute-Saône" },
      { code: "71", name: "Saône-et-Loire" },
      { code: "72", name: "Sarthe" },
      { code: "73", name: "Savoie" },
      { code: "74", name: "Haute-Savoie" },
      { code: "75", name: "Paris" },
      { code: "76", name: "Seine-Maritime" },
      { code: "77", name: "Seine-et-Marne" },
      { code: "78", name: "Yvelines" },
      { code: "79", name: "Deux-Sèvres" },
      { code: "80", name: "Somme" },
      { code: "81", name: "Tarn" },
      { code: "82", name: "Tarn-et-Garonne" },
      { code: "83", name: "Var" },
      { code: "84", name: "Vaucluse" },
      { code: "85", name: "Vendée" },
      { code: "86", name: "Vienne" },
      { code: "87", name: "Haute-Vienne" },
      { code: "88", name: "Vosges" },
      { code: "89", name: "Yonne" },
      { code: "90", name: "Territoire de Belfort" },
      { code: "91", name: "Essonne" },
      { code: "92", name: "Hauts-de-Seine" },
      { code: "93", name: "Seine-Saint-Denis" },
      { code: "94", name: "Val-de-Marne" },
      { code: "95", name: "Val-d'Oise" },
    ],
    JP: [
      { code: "01", name: "Hokkaido" },
      { code: "02", name: "Aomori" },
      { code: "03", name: "Iwate" },
      { code: "04", name: "Miyagi" },
      { code: "05", name: "Akita" },
      { code: "06", name: "Yamagata" },
      { code: "07", name: "Fukushima" },
      { code: "08", name: "Ibaraki" },
      { code: "09", name: "Tochigi" },
      { code: "10", name: "Gunma" },
      { code: "11", name: "Saitama" },
      { code: "12", name: "Chiba" },
      { code: "13", name: "Tokyo" },
      { code: "14", name: "Kanagawa" },
      { code: "15", name: "Niigata" },
      { code: "16", name: "Toyama" },
      { code: "17", name: "Ishikawa" },
      { code: "18", name: "Fukui" },
      { code: "19", name: "Yamanashi" },
      { code: "20", name: "Nagano" },
      { code: "21", name: "Gifu" },
      { code: "22", name: "Shizuoka" },
      { code: "23", name: "Aichi" },
      { code: "24", name: "Mie" },
      { code: "25", name: "Shiga" },
      { code: "26", name: "Kyoto" },
      { code: "27", name: "Osaka" },
      { code: "28", name: "Hyogo" },
      { code: "29", name: "Nara" },
      { code: "30", name: "Wakayama" },
      { code: "31", name: "Tottori" },
      { code: "32", name: "Shimane" },
      { code: "33", name: "Okayama" },
      { code: "34", name: "Hiroshima" },
      { code: "35", name: "Yamaguchi" },
      { code: "36", name: "Tokushima" },
      { code: "37", name: "Kagawa" },
      { code: "38", name: "Ehime" },
      { code: "39", name: "Kochi" },
      { code: "40", name: "Fukuoka" },
      { code: "41", name: "Saga" },
      { code: "42", name: "Nagasaki" },
      { code: "43", name: "Kumamoto" },
      { code: "44", name: "Oita" },
      { code: "45", name: "Miyazaki" },
      { code: "46", name: "Kagoshima" },
      { code: "47", name: "Okinawa" },
    ],
    CN: [
      { code: "BJ", name: "Beijing" },
      { code: "TJ", name: "Tianjin" },
      { code: "HE", name: "Hebei" },
      { code: "SX", name: "Shanxi" },
      { code: "NM", name: "Inner Mongolia" },
      { code: "LN", name: "Liaoning" },
      { code: "JL", name: "Jilin" },
      { code: "HL", name: "Heilongjiang" },
      { code: "SH", name: "Shanghai" },
      { code: "JS", name: "Jiangsu" },
      { code: "ZJ", name: "Zhejiang" },
      { code: "AH", name: "Anhui" },
      { code: "FJ", name: "Fujian" },
      { code: "JX", name: "Jiangxi" },
      { code: "SD", name: "Shandong" },
      { code: "HA", name: "Henan" },
      { code: "HB", name: "Hubei" },
      { code: "HN", name: "Hunan" },
      { code: "GD", name: "Guangdong" },
      { code: "GX", name: "Guangxi" },
      { code: "HI", name: "Hainan" },
      { code: "CQ", name: "Chongqing" },
      { code: "SC", name: "Sichuan" },
      { code: "GZ", name: "Guizhou" },
      { code: "YN", name: "Yunnan" },
      { code: "XZ", name: "Tibet" },
      { code: "SN", name: "Shaanxi" },
      { code: "GS", name: "Gansu" },
      { code: "QH", name: "Qinghai" },
      { code: "NX", name: "Ningxia" },
      { code: "XJ", name: "Xinjiang" },
      { code: "HK", name: "Hong Kong" },
      { code: "MO", name: "Macau" },
    ],
  };
