export const nigeriaData = {
  Abia: [
    "Aba",
    "Umuahia",
    "Arochukwu",
    "Bende",
    "Ohafia",
    "Ikwuano",
    "Isiala Ngwa",
    "Isuikwuato",
    "Obi Ngwa",
    "Osisioma",
    "Ugwunagbo",
    "Ukwa East",
    "Ukwa West",
    "Umu Nneochi",
  ],
  Adamawa: [
    "Yola",
    "Mubi",
    "Numan",
    "Jimeta",
    "Ganye",
    "Song",
    "Gombi",
    "Hong",
    "Michika",
    "Madagali",
    "Maiha",
    "Shelleng",
    "Fufore",
    "Girei",
  ],
  "Akwa Ibom": [
    "Uyo",
    "Ikot Ekpene",
    "Eket",
    "Oron",
    "Ikot Abasi",
    "Abak",
    "Etinan",
    "Ikono",
    "Ini",
    "Itu",
    "Nsit Ibom",
    "Uruan",
    "Esit Eket",
    "Ibeno",
  ],
  Anambra: [
    "Awka",
    "Onitsha",
    "Nnewi",
    "Ekwulobia",
    "Ihiala",
    "Aguata",
    "Anaocha",
    "Ayamelum",
    "Dunukofia",
    "Ekwusigo",
    "Idemili North",
    "Idemili South",
    "Njikoka",
    "Ogbaru",
    "Oyi",
  ],
  Bauchi: [
    "Bauchi",
    "Azare",
    "Misau",
    "Jama'are",
    "Katagum",
    "Dass",
    "Bogoro",
    "Tafawa Balewa",
    "Warji",
    "Giade",
    "Kirfi",
    "Alkaleri",
    "Darazo",
    "Ningi",
    "Toro",
  ],
  Bayelsa: [
    "Yenagoa",
    "Brass",
    "Sagbama",
    "Nembe",
    "Ogbia",
    "Ekeremor",
    "Kolokuma Opokuma",
    "Southern Ijaw",
  ],
  Benue: [
    "Makurdi",
    "Gboko",
    "Otukpo",
    "Katsina-Ala",
    "Vandeikya",
    "Ado",
    "Agatu",
    "Apa",
    "Buruku",
    "Guma",
    "Gwer East",
    "Gwer West",
    "Konshisha",
    "Kwande",
    "Logo",
    "Obi",
    "Ogbadibo",
    "Ohimini",
    "Oju",
    "Okpokwu",
    "Tarka",
    "Ukum",
    "Ushongo",
  ],
  Borno: [
    "Maiduguri",
    "Biu",
    "Bama",
    "Dikwa",
    "Monguno",
    "Ngala",
    "Kukawa",
    "Gubio",
    "Magumeri",
    "Konduga",
    "Jere",
    "Mafa",
    "Kaga",
    "Nganzai",
    "Mobbar",
    "Abadam",
    "Hawul",
    "Chibok",
    "Damboa",
    "Gwoza",
    "Askira Uba",
    "Bayo",
    "Kala Balge",
    "Kwaya Kusar",
    "Marte",
    "Shani",
  ],
  "Cross River": [
    "Calabar",
    "Ogoja",
    "Ikom",
    "Obudu",
    "Ugep",
    "Akpabuyo",
    "Odukpani",
    "Akamkpa",
    "Biase",
    "Abi",
    "Yarkur",
    "Odubra",
    "Boki",
    "Yala",
    "Obanliku",
    "Etung",
    "Bekwara",
    "Bakassi",
  ],
  Delta: [
    "Asaba",
    "Warri",
    "Sapele",
    "Ughelli",
    "Agbor",
    "Ozoro",
    "Kwale",
    "Oleh",
    "Abraka",
    "Oghara",
    "Effurun",
    "Okpanam",
    "Issele-Uku",
    "Obiaruku",
    "Patani",
    "Bomadi",
    "Burutu",
    "Forcados",
  ],
  Ebonyi: [
    "Abakaliki",
    "Afikpo",
    "Onueke",
    "Ezza",
    "Ikwo",
    "Ishielu",
    "Izzi",
    "Ohaozara",
    "Ohaukwu",
    "Onicha",
    "Ezza South",
    "Ivo",
  ],
  Edo: [
    "Benin City",
    "Auchi",
    "Ekpoma",
    "Uromi",
    "Irrua",
    "Ubiaja",
    "Igarra",
    "Okada",
    "Ewu",
    "Afuze",
    "Fugar",
    "Agenebode",
    "Uzairue",
    "Jattu",
    "Sabongida Ora",
  ],
  Ekiti: [
    "Ado-Ekiti",
    "Ikere",
    "Ilawe",
    "Ijero",
    "Ikole",
    "Omuo",
    "Aramoko",
    "Efon",
    "Emure",
    "Gbonyin",
    "Ido",
    "Ilejemeje",
    "Irepodun",
    "Ise Orun",
    "Moba",
    "Oye",
  ],
  Enugu: [
    "Enugu",
    "Nsukka",
    "Oji River",
    "Agbani",
    "Awgu",
    "Ezeagu",
    "Igbo Etiti",
    "Igbo Eze North",
    "Igbo Eze South",
    "Isi Uzo",
    "Nkanu East",
    "Nkanu West",
    "Udi",
    "Udenu",
    "Uzo Uwani",
  ],
  FCT: ["Abuja", "Gwagwalada", "Kuje", "Bwari", "Kwali", "Abaji"],
  Gombe: [
    "Gombe",
    "Billiri",
    "Kaltungo",
    "Deba",
    "Nafada",
    "Akko",
    "Balanga",
    "Dukku",
    "Funakaye",
    "Kwami",
    "Shongom",
    "Yamaltu Deba",
  ],
  Imo: [
    "Owerri",
    "Orlu",
    "Okigwe",
    "Mbaise",
    "Oguta",
    "Ngor Okpala",
    "Ihitte Uboma",
    "Ezinihitte",
    "Ideato North",
    "Ideato South",
    "Ikeduru",
    "Isiala Mbano",
    "Isu",
    "Mbaitoli",
    "Njaba",
    "Nkwerre",
    "Nwangele",
    "Obowo",
    "Ohaji Egbema",
    "Onuimo",
    "Orsu",
    "Oru East",
    "Oru West",
    "Owerri Municipal",
    "Owerri North",
    "Owerri West",
  ],
  Jigawa: [
    "Dutse",
    "Hadejia",
    "Birnin Kudu",
    "Gumel",
    "Kazaure",
    "Ringim",
    "Jahun",
    "Miga",
    "Auyo",
    "Babura",
    "Biriniwa",
    "Buji",
    "Gagarawa",
    "Garki",
    "Guri",
    "Gwaram",
    "Gwiwa",
    "Kafin Hausa",
    "Kaugama",
    "Kiri Kasamma",
    "Kiyawa",
    "Maigatari",
    "Malam Madori",
    "Roni",
    "Sule Tankar Kar",
    "Taura",
    "Yankwashi",
  ],
  Kaduna: [
    "Kaduna",
    "Zaria",
    "Kafanchan",
    "Kagoro",
    "Soba",
    "Birnin Gwari",
    "Chikun",
    "Giwa",
    "Igabi",
    "Ikara",
    "Jaba",
    "Jema'a",
    "Kachia",
    "Kagarko",
    "Kajuru",
    "Kaura",
    "Kauru",
    "Kubau",
    "Kudan",
    "Lere",
    "Makarfi",
    "Sabon Gari",
    "Sanga",
    "Zango Kataf",
  ],
  Kano: [
    "Kano",
    "Wudil",
    "Gwarzo",
    "Rano",
    "Karaye",
    "Rimin Gado",
    "Ungogo",
    "Dala",
    "Gwale",
    "Tarauni",
    "Nassarawa",
    "Fagge",
    "Kumbotso",
    "Tofa",
    "Rogo",
    "Kibiya",
    "Tudun Wada",
    "Garko",
    "Kiru",
    "Madobi",
    "Minjibir",
    "Shanono",
    "Sumaila",
    "Tsanyawa",
    "Bunkure",
    "Karaye",
    "Kunchi",
    "Makoda",
    "Warawa",
    "Gaya",
    "Ajingi",
    "Albasu",
    "Bagwai",
    "Bebeji",
    "Bichi",
    "Dambatta",
    "Dawakin Kudu",
    "Dawakin Tofa",
    "Doguwa",
    "Gabasawa",
    "Gezawa",
    "Kabo",
  ],
  Katsina: [
    "Katsina",
    "Daura",
    "Funtua",
    "Malumfashi",
    "Dutsin-Ma",
    "Bindawa",
    "Charanchi",
    "Dan Musa",
    "Dandume",
    "Danja",
    "Dutsi",
    "Faskari",
    "Ingawa",
    "Jibia",
    "Kafur",
    "Kaita",
    "Kankara",
    "Kankia",
    "Kurfi",
    "Kusada",
    "Mai'Adua",
    "Mani",
    "Mashi",
    "Matazu",
    "Musawa",
    "Rimi",
    "Sabuwa",
    "Safana",
    "Sandamu",
    "Zango",
    "Bakori",
    "Batagarawa",
    "Batsari",
    "Baure",
  ],
  Kebbi: [
    "Birnin Kebbi",
    "Argungu",
    "Yauri",
    "Zuru",
    "Jega",
    "Aleiro",
    "Arewa",
    "Augie",
    "Bagudo",
    "Bunza",
    "Dandi",
    "Fakai",
    "Gwandu",
    "Kalgo",
    "Koko Besse",
    "Maiyama",
    "Ngaski",
    "Sakaba",
    "Shanga",
    "Suru",
    "Wasagu Danko",
  ],
  Kogi: [
    "Lokoja",
    "Okene",
    "Idah",
    "Kabba",
    "Ankpa",
    "Anyigba",
    "Ajaokuta",
    "Dekina",
    "Ejule",
    "Bassa",
    "Adavi",
    "Ofu",
    "Yagba East",
    "Yagba West",
    "Mopa Muro",
    "Okehi",
    "Okene",
    "Olamaboro",
    "Omala",
    "Ibaji",
    "Igalamela",
    "Ijumu",
  ],
  Kwara: [
    "Ilorin",
    "Offa",
    "Omu-Aran",
    "Lafiagi",
    "Kaiama",
    "Jebba",
    "Esie",
    "Oro",
    "Share",
    "Shonga",
    "Erin Ile",
    "Igbaja",
    "Ajase Ipo",
    "Oke Ero",
    "Patigi",
    "Asa",
    "Baruten",
    "Edu",
    "Ekiti",
    "Ifelodun",
    "Ilorin East",
    "Ilorin South",
    "Ilorin West",
    "Irepodun",
    "Isin",
    "Moro",
    "Oyun",
  ],
  Lagos: [
    "Lagos",
    "Ikeja",
    "Epe",
    "Ikorodu",
    "Badagry",
    "Agege",
    "Alimosho",
    "Amuwo Odofin",
    "Apapa",
    "Eti Osa",
    "Ibeju Lekki",
    "Ifako Ijaye",
    "Kosofe",
    "Lagos Island",
    "Lagos Mainland",
    "Mushin",
    "Ojo",
    "Oshodi Isolo",
    "Shomolu",
    "Surulere",
    "Ajeromi Ifelodun",
    "Victoria Island",
    "Lekki",
    "Ajah",
    "Maryland",
    "Yaba",
    "Ebute Metta",
    "Festac",
    "Satellite Town",
  ],
  Nasarawa: [
    "Lafia",
    "Keffi",
    "Akwanga",
    "Nasarawa",
    "Doma",
    "Karu",
    "Kokona",
    "Nasarawa Egon",
    "Obi",
    "Toto",
    "Wamba",
    "Awe",
    "Keana",
  ],
  Niger: [
    "Minna",
    "Bida",
    "Kontagora",
    "Suleja",
    "New Bussa",
    "Agaie",
    "Agwara",
    "Borgu",
    "Bosso",
    "Chanchaga",
    "Edati",
    "Gbako",
    "Gurara",
    "Katcha",
    "Lapai",
    "Lavun",
    "Magama",
    "Mariga",
    "Mashegu",
    "Mokwa",
    "Muya",
    "Paikoro",
    "Rafi",
    "Rijau",
    "Shiroro",
    "Tafa",
    "Wushishi",
  ],
  Ogun: [
    "Abeokuta",
    "Sagamu",
    "Ijebu Ode",
    "Ilaro",
    "Ota",
    "Ifo",
    "Ewekoro",
    "Obafemi Owode",
    "Odeda",
    "Odogbolu",
    "Ogun Waterside",
    "Remo North",
    "Shagamu",
    "Abeokuta North",
    "Abeokuta South",
    "Ado Odo Ota",
    "Yewa North",
    "Yewa South",
    "Ijebu East",
    "Ijebu North",
    "Ijebu North East",
    "Ikenne",
    "Imeko Afon",
    "Ipokia",
  ],
  Ondo: [
    "Akure",
    "Ondo",
    "Owo",
    "Ikare",
    "Okitipupa",
    "Ore",
    "Ode Irele",
    "Igbokoda",
    "Akoko",
    "Idanre",
    "Ifedore",
    "Ilaje",
    "Ile Oluji Okeigbo",
    "Irele",
    "Odigbo",
    "Ose",
    "Akoko North East",
    "Akoko North West",
    "Akoko South East",
    "Akoko South West",
    "Akure North",
    "Akure South",
    "Ese Odo",
  ],
  Osun: [
    "Osogbo",
    "Ile-Ife",
    "Ilesha",
    "Ede",
    "Iwo",
    "Ikirun",
    "Ikire",
    "Inisa",
    "Ipetumodu",
    "Iragbiji",
    "Ila Orangun",
    "Ejigbo",
    "Gbongan",
    "Ibokun",
    "Ife Central",
    "Ife East",
    "Ife North",
    "Ife South",
    "Ifedayo",
    "Ifelodun",
    "Ilesha East",
    "Ilesha West",
    "Irepodun",
    "Irewole",
    "Isokan",
    "Obokun",
    "Odo Otin",
    "Ola Oluwa",
    "Olorunda",
    "Oriade",
    "Orolu",
    "Aiyedade",
    "Aiyedire",
    "Atakumosa East",
    "Atakumosa West",
    "Boluwaduro",
    "Boripe",
    "Ede North",
    "Ede South",
    "Egbedore",
  ],
  Oyo: [
    "Ibadan",
    "Ogbomoso",
    "Oyo",
    "Iseyin",
    "Saki",
    "Shaki",
    "Kishi",
    "Igboho",
    "Eruwa",
    "Lanlate",
    "Igbo Ora",
    "Jobele",
    "Fiditi",
    "Ago Are",
    "Lalupon",
    "Moniya",
    "Ojoo",
    "Akinyele",
    "Lagelu",
    "Ona Ara",
    "Oluyole",
    "Ido",
    "Egbeda",
    "Ibadan North",
    "Ibadan North East",
    "Ibadan North West",
    "Ibadan South East",
    "Ibadan South West",
    "Afijio",
    "Atiba",
    "Atisbo",
    "Ibarapa Central",
    "Ibarapa East",
    "Ibarapa North",
    "Irepo",
    "Itesiwaju",
    "Iwajowa",
    "Kajola",
    "Ogbomoso North",
    "Ogbomoso South",
    "Ogo Oluwa",
    "Olorunsogo",
    "Orelope",
    "Ori Ire",
    "Oyo East",
    "Oyo West",
    "Saki East",
    "Saki West",
    "Surulere",
  ],
  Plateau: [
    "Jos",
    "Bukuru",
    "Shendam",
    "Pankshin",
    "Vom",
    "Mangu",
    "Bokkos",
    "Langtang",
    "Wase",
    "Barkin Ladi",
    "Bassa",
    "Jos East",
    "Jos North",
    "Jos South",
    "Kanam",
    "Kanke",
    "Langtang North",
    "Langtang South",
    "Mikang",
    "Qua'an Pan",
    "Riyom",
  ],
  Rivers: [
    "Port Harcourt",
    "Obio-Akpor",
    "Okrika",
    "Ahoada",
    "Bonny",
    "Degema",
    "Eleme",
    "Emohua",
    "Etche",
    "Gokana",
    "Ikwerre",
    "Khana",
    "Ogba Egbema Ndoni",
    "Ogu Bolo",
    "Omuma",
    "Opobo Nkoro",
    "Oyigbo",
    "Tai",
    "Abua Odual",
    "Ahoada East",
    "Ahoada West",
    "Akuku Toru",
    "Andoni",
    "Asari Toru",
  ],
  Sokoto: [
    "Sokoto",
    "Tambuwal",
    "Gwadabawa",
    "Bodinga",
    "Wamako",
    "Binji",
    "Dange Shuni",
    "Gada",
    "Goronyo",
    "Gudu",
    "Illela",
    "Isa",
    "Kebbe",
    "Kware",
    "Rabah",
    "Sabon Birni",
    "Shagari",
    "Silame",
    "Sokoto North",
    "Sokoto South",
    "Tangaza",
    "Tureta",
    "Wurno",
    "Yabo",
  ],
  Taraba: [
    "Jalingo",
    "Wukari",
    "Bali",
    "Takum",
    "Ibi",
    "Mutum Biyu",
    "Serti",
    "Zing",
    "Kurmi",
    "Sardauna",
    "Gashaka",
    "Karim Lamido",
    "Lau",
    "Ussa",
    "Yorro",
    "Ardo Kola",
    "Donga",
  ],
  Yobe: [
    "Damaturu",
    "Potiskum",
    "Gashua",
    "Nguru",
    "Geidam",
    "Bade",
    "Bursari",
    "Fika",
    "Fune",
    "Gujba",
    "Gulani",
    "Jakusko",
    "Karasuwa",
    "Machina",
    "Nangere",
    "Tarmua",
    "Yunusari",
    "Yusufari",
  ],
  Zamfara: [
    "Gusau",
    "Kaura Namoda",
    "Talata Mafara",
    "Anka",
    "Bungudu",
    "Birnin Magaji Kiyaw",
    "Bukkuyum",
    "Chafe",
    "Gummi",
    "Kauran Namoda",
    "Maradun",
    "Maru",
    "Shinkafi",
    "Tsafe",
    "Zurmi",
  ],
};

export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];
